/* Assemble all pages for export */
export ResetPasswordPage from './ResetPasswordPage/index';
export AboutPage from './AboutPage/index';
export MembersPage from './MembersPage/index';
export ArchivePage from './ArchivePage/index';
export UserProfilePage from './UserProfilePage/index';
export CarouselWidgetPage from './CarouselWidgetPage/index';
export NotYetReadyPage from './NotYetReadyPage/index';
export MentorshipPage from './MentorshipPage/index';
export MeetupsPage from './MeetupsPage/index';
export LogoutPage from './LogoutPage/index';
export SearchPage from './SearchPage/index';
export SingleArticlePage from './SingleArticlePage/index';
export CmsEditorPage from './CmsEditorPage/index';
export SignupPage from './SignupPage/index';
export LoginPage from './LoginPage/index';
export ContentDashboardPage from './ContentDashboardPage/index';
export NotFoundPage from './NotFoundPage/index';
export LandingPage from './LandingPage/index';
