export const APP_SET_MOBILE = 'APP_SET_MOBILE';
export const APP_ON_TOGGLE_NAV = 'APP_ON_TOGGLE_NAV';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const INVALIDATE_AUTH_USER = 'INVALIDATE_AUTH_USER';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
