export const TOGGLE_FEEDBACK_MODAL = 'TOGGLE_ADD_FEEDBACK';
export const FEEDBACK_SUBMISSION_INITIATION = 'FEEDBACK_SUBMISSION_INITIATION';
export const FEEDBACK_SUBMISSION_MESSAGE = 'FEEDBACK_SUBMISSION_MESSAGE';
export const FEEDBACK_SUBMISSION_ERROR = 'FEEDBACK_SUBMISSION_ERROR';
