export const FEATURED_ARTICLES_INITIATION = 'FEATURED_ARTICLES_INITIATION';
export const FEATURED_ARTICLES_SUCCESS = 'FEATURED_ARTICLES_SUCCESS';
export const FEATURE_ARTICLES_FAILURE = 'FEATURE_ARTICLES_FAILURE';
export const CLEAR_LANDING_ERRORS = 'CLEAR_LANDING_ERRORS';
