export const FEATURED_ARTICLES_INITIATION = 'FEATURED_ARTICLES_INITIATION';
export const FEATURED_ARTICLES_SUCCESS = 'FEATURED_ARTICLES_SUCCESS';
export const FEATURE_ARTICLES_FAILURE = 'FEATURE_ARTICLES_FAILURE';
export const CLEAR_LANDING_ERROR = 'CLEAR_LANDING_ERROR';
export const SPOTLIGHTED_IMAGES_INITIATION = 'SPOTLIGHTED_IMAGES_INITIATION';
export const SPOTLIGHTED_IMAGES_SUCCESS = 'SPOTLIGHTED_IMAGES_SUCCESS';
export const SPOTLIGHTED_IMAGES_FAILURE = 'SPOTLIGHTED_IMAGES_FAILURE';
