export const fields = {
  emailInput: {
    name: 'emailInput',
    value: 'demo@udacity.com',
    initialValue: '',
    valid: true,
    invalid: false,
    dirty: true,
    pristine: false,
    active: false,
    touched: true,
    visited: true,
    autofilled: false,
  },
  passwordInput: {
    name: 'passwordInput',
    value: 'Password123!',
    initialValue: '',
    valid: true,
    invalid: false,
    dirty: true,
    pristine: false,
    active: false,
    touched: false,
    visited: false,
    autofilled: false,
  },
};
