export const DASHBOARD_ARTICLES_INITIATION = 'DASHBOARD_ARTICLES_INITIATION';
export const DASHBOARD_ARTICLES_SUCCESS = 'DASHBOARD_ARTICLES_SUCCESS';
export const DASHBOARD_ARTICLES_FAILURE = 'DASHBOARD_ARTICLES_FAILURE';
export const CLEAR_DASHBOARD_ERROR = 'CLEAR_DASHBOARD_ERROR';
