export const SEARCH_ARTICLES_INITIATION = 'SEARCH_ARTICLES_INITIATION';
export const SEARCH_ARTICLES_SUCCESS = 'SEARCH_ARTICLES_SUCCESS';
export const SEARCH_ARTICLES_FAILURE = 'SEARCH_ARTICLES_FAILURE';
export const CLEAR_SEARCH_ERROR = 'CLEAR_SEARCH_ERROR';
