export const ADMIN_DASHBOARD_SET_ACTIVE_TAB = 'ADMIN_DASHBOARD_SET_ACTIVE_TAB';
export const ADMIN_DASHBOARD_SET_USERS = 'ADMIN_DASHBOARD_SET_USERS';
export const ADMIN_DASHBOARD_SET_ARTICLES = 'ADMIN_DASHBOARD_SET_ARTICLES';
export const ADMIN_DASHBOARD_SET_USERS_PAGE = 'ADMIN_DASHBOARD_SET_USERS_PAGE';
export const ADMIN_DASHBOARD_SET_ARTICLES_PAGE = 'ADMIN_DASHBOARD_SET_ARTICLES_PAGE';
export const ADMIN_DASHBOARD_SET_USER_EDITING = 'ADMIN_DASHBOARD_SET_USER_EDITING';
export const ADMIN_DASHBOARD_CLEAR_USER_EDITING = 'ADMIN_DASHBOARD_CLEAR_USER_EDITING';
export const ADMIN_DASHBOARD_TOGGLE_ASIDE = 'ADMIN_DASHBOARD_TOGGLE_ASIDE';
export const ADMIN_DASHBOARD_SET_ERROR = 'ADMIN_DASHBOARD_SET_ERROR';
export const ADMIN_DASHBOARD_CLEAR_ERROR = 'ADMIN_DASHBOARD_CLEAR_ERROR';
export const ADMIN_DASHBOARD_SET_SORT_OPTIONS = 'ADMIN_DASHBOARD_SET_SORT_OPTIONS';
export const ADMIN_DASHBOARD_OPEN_MODAL = 'ADMIN_DASHBOARD_OPEN_MODAL';
export const ADMIN_DASHBOARD_CLOSE_MODAL = 'ADMIN_DASHBOARD_CLOSE_MODAL';
export const ADMIN_DASHBOARD_EDIT_AVATAR_INPUT = 'ADMIN_DASHBOARD_EDIT_AVATAR_INPUT';
export const ADMIN_DASHBOARD_CANCEL_ARTICLE_DELETION = 'ADMIN_DASHBOARD_CANCEL_ARTICLE_DELETION';
export const ADMIN_DASHBOARD_OPEN_CONFIRMATION_MODAL = 'ADMIN_DASHBOARD_OPEN_CONFIRMATION_MODAL';
export const DASHBOARD_DELETE_ARTICLE_INITIATION = 'DASHBOARD_DELETE_ARTICLE_INITIATION';
export const DASHBOARD_DELETE_ARTICLE_SUCCESS = 'DASHBOARD_DELETE_ARTICLE_SUCCESS';
export const DASHBOARD_DELETE_ARTICLE_FAILURE = 'DASHBOARD_DELETE_ARTICLE_FAILURE';
export const ADMIN_DASHBOARD_CLEAR_MESSAGE = 'ADMIN_DASHBOARD_CLEAR_MESSAGE';
export const ADMIN_DASHBOARD_SET_FEEDBACK_PAGE = 'ADMIN_DASHBOARD_SET_FEEDBACK_PAGE';
export const ADMIN_DASHBOARD_SET_FEEDBACK = 'ADMIN_DASHBOARD_SET_FEEDBACK';
export const ADMIN_DASHBOARD_SHOW_FEEDBACK_MODAL = 'ADMIN_DASHBOARD_SHOW_FEEDBACK_MODAL';
export const ADMIN_DASHBOARD_DISMISS_FEEDBACK_MODAL = 'ADMIN_DASHBOARD_DISMISS_FEEDBACK_MODAL';
export const ADMIN_DASHBOARD_SET_SORT_OPTIONS_FEEDBACK =
  'ADMIN_DASHBOARD_SET_SORT_OPTIONS_FEEDBACK';
export const ADMIN_DASHBOARD_SET_SORT_OPTIONS_ARTICLES =
  'ADMIN_DASHBOARD_SET_SORT_OPTIONS_ARTICLES';
