export const ADMIN_DASHBOARD_SET_ACTIVE_TAB = 'ADMIN_DASHBOARD_SET_ACTIVE_TAB';
export const ADMIN_DASHBOARD_SET_USERS = 'ADMIN_DASHBOARD_SET_USERS';
export const ADMIN_DASHBOARD_SET_ARTICLES = 'ADMIN_DASHBOARD_SET_ARTICLES';
export const ADMIN_DASHBOARD_SET_USERS_PAGE = 'ADMIN_DASHBOARD_SET_USERS_PAGE';
export const ADMIN_DASHBOARD_SET_ARTICLES_PAGE = 'ADMIN_DASHBOARD_SET_ARTICLES_PAGE';
export const ADMIN_DASHBOARD_SET_USER_EDITING = 'ADMIN_DASHBOARD_SET_USER_EDITING';
