export const CAROUSEL_ADD_IMAGE = 'CAROUSEL_ADD_IMAGE';
export const CAROUSEL_REMOVE_IMAGE = 'CAROUSEL_REMOVE_IMAGE';
export const CAROUSEL_EDIT_IMAGE = 'CAROUSEL_EDIT_IMAGE';
export const CAROUSEL_SET_EDITING = 'CAROUSEL_SET_EDITING';
export const CAROUSEL_CANCEL_EDITING = 'CAROUSEL_CANCEL_EDITING';
export const CAROUSEL_SET_IMAGES = 'CAROUSEL_SET_IMAGES';
