export const LOGIN_INITIATE_REQUEST = 'LOGIN_INITIATE_REQUEST';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_CLEAR_ERROR = 'LOGIN_CLEAR_ERROR';
export const LOGIN_SET_MESSAGE = 'LOGIN_SET_MESSAGE';
export const LOGIN_CLEAR_MESSAGE = 'LOGIN_CLEAR_MESSAGE';
