export const START_LOGIN_REQUEST = 'START_LOGIN_REQUEST';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
