export const START_LOGIN_REQUEST = 'START_LOGIN_REQUEST';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const LOGIN_SET_MESSAGE = 'LOGIN_SET_MESSAGE';
export const LOGIN_CLEAR_MESSAGE = 'LOGIN_CLEAR_MESSAGE';
