export const SUBMIT_ARTICLE_INITIATION = 'SUBMIT_ARTICLE_INITIATION';
export const SUBMIT_ARTICLE_FAILURE = 'SUBMIT_ARTICLE_FAILURE';
export const SUBMIT_ARTICLE_SUCCESS = 'SUBMIT_ARTICLE_SUCCESS';
export const CLEAR_CMS_ERRORS = 'CLEAR_CMS_ERRORS';
export const CLEAR_CMS_MESSAGE = 'CLEAR_CMS_MESSAGE';
