export const RESET_PASSWORD_REQUEST_INITIATION = 'RESET_PASSWORD_REQUEST_INITIATION';
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILURE = 'RESET_PASSWORD_REQUEST_FAILURE';
