export const SIGNUP_REQUEST_INITIATION = 'SIGNUP_REQUEST_INITIATION';
export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE';
export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';
